Ecommerce_MVC_Core/Models/Admin/Unit.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ecommerce_MVC_Core.Data;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Ecommerce_MVC_Core.Models.Admin
{
    public class Unit:BaseEntity
    {
        public string Name { get; set; }
        public string Description { get; set; }

        public ICollection<Product> Products { get; set; }
    }

    public class UnitMap
    {
        public UnitMap(EntityTypeBuilder<Unit> entityTypeBuilder)
        {
            entityTypeBuilder.HasKey(x => x.Id);
            entityTypeBuilder.Property(x => x.Name).HasMaxLength(100);
            entityTypeBuilder.Property(x => x.Description).HasMaxLength(200);
        }
    }
}

Ecommerce_MVC_Core/Controllers/Admin/UnitsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ecommerce_MVC_Core.Data;
using Ecommerce_MVC_Core.Models.Admin;
using Ecommerce_MVC_Core.Repository;
using Ecommerce_MVC_Core.ViewModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Ecommerce_MVC_Core.Controllers.Admin
{
    public class UnitsController : Controller
    {


        private readonly IUnitOfWork _unitOfWork;

        public UnitsController(
            IUnitOfWork unitOfWork
        )
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index(string search="")
        {
            List<UnitListViewModel> model = new List<UnitListViewModel>();
            var dbData = _unitOfWork.Repository<Unit>().GetAllInclude(x => x.Products);
            if (!String.IsNullOrEmpty(search))
            {
                dbData=dbData.Where(x => x.Name.ToLower().Contains(search.ToLower())).ToList();

            }

            foreach (var b in dbData)
            {
                
                UnitListViewModel unit = new UnitListViewModel
                {
                    Id = b.Id,
                    Name = b.Name,
                    Description = b.Description,
                    TotalProducts = b.Products.Count
                };

                model.Add(unit);
            }


            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> AddEditUnit(int id)
        {
            UnitViewModel model = new UnitViewModel();
            if (id > 0)
            {
                Unit payment = await _unitOfWork.Repository<Unit>().GetByIdAsync(id);
                model.Name = payment.Name;
                model.Description = payment.Description;
            }

            return PartialView("_AddEditUnit", model);
        }


        [HttpPost]
        public async Task<IActionResult> AddEditUnit(int id, UnitViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("_AddEditUnit", model);
            }

            if (id > 0)
            {
                Unit unit = await _unitOfWork.Repository<Unit>().GetByIdAsync(id);
                if (unit != null)
                {
                    unit.Name = model.Name;
                    unit.ModifiedDate = DateTime.Now;
                    unit.Description = model.Description;
                    await _unitOfWork.Repository<Unit>().UpdateAsync(unit);
                }
            }
            else
            {
                Unit unit = new Unit
                {
                    Name = model.Name,
                    ModifiedDate = DateTime.Now,
                    AddedDate = DateTime.Now,
                    Description = model.Description,
                };
                await _unitOfWork.Repository<Unit>().InsertAsync(unit);
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> DeleteUnit(int id)
        {
            Unit unit = await _unitOfWork.Repository<Unit>().GetByIdAsync(id);

            return PartialView("_DeleteUnit", unit?.Name);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteUnit(int id, IFormCollection form)
        {
            Unit unit = await _unitOfWork.Repository<Unit>().GetByIdAsync(id);
            if (unit != null)
            {
                await _unitOfWork.Repository<Unit>().DeleteAsync(unit);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Ecommerce_MVC_Core/Views/Units/Index.cshtml
@model IEnumerable<Ecommerce_MVC_Core.ViewModel.UnitListViewModel>
@{
    ViewData["Title"] = "Index";
}

<div class="col-md-2">
    <a id="createModel" data-toggle="modal" asp-controller="Units" asp-action="AddEditUnit" class="btn btn-info" data-target="#modal-popUP">
        <i class="glyphicon glyphicon-plus"></i>Add
    </a>
</div>
<div class="col-md-3">
    <form method="post" asp-action="Index" class="form-inline">
        <div class="form-horizontal">
            <div class="form-group">
                <input type="text" name="search" value="@Html.ViewBag.SearchString" class="form-control" />
                <input type="submit" value="Search" class="btn btn-default pull-right" />

            </div>
        </div>
    </form>
</div>

@{
    if (Model.ToList().Count <= 0)
    {
        <h1>No Unit Added Yet</h1>
    }
    else
    {
        <table class="table table-responsive table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Total Products</th>
                    <th>Action</th>
                </tr>
            </thead>

            <tbody>
                @{
                    int count = 1;
                    foreach (var item in Model)
                    {
                        <tr>
                            <td>@count</td>
                            <td>
                                @item.Name
                            </td>
                            <td>@item.Description</td>
                            <td>@item.TotalProducts</td>
                            <td>
                                <a id="editUserModal" data-toggle="modal" asp-action="AddEditUnit" asp-route-id="@item.Id" data-target="#modal-popUP"
                                   class="btn btn-info">
                                    <i class="glyphicon glyphicon-pencil"></i>  Edit
                                </a>
                                <a id="deleteUserModal" data-toggle="modal" asp-action="DeleteUnit" asp-route-id="@item.Id" data-target="#modal-popUP" class="btn btn-danger">
                                    <i class="glyphicon glyphicon-trash"></i>  Delete
                                </a>
                            </td>
                        </tr>
                        count++;
                    }
                }
            </tbody>
        </table>
    }
}
@Html.Partial("_Modal", new BootstrapModel { ID = "modal-popUP", AreaLabeledId = "modal-popUP-label", Size = ModalSize.Medium })

Ecommerce_MVC_Core/Views/Units/_AddEditUnit.cshtml
@model Ecommerce_MVC_Core.ViewModel.UnitViewModel
<form asp-action="AddEditUnit" id="frm">
    <div class="form-horizontal">
        @await Html.PartialAsync("_ModalHeader", new ModalHeader { Heading = $"{(Model.Id <= 0 ? "Add" : "Edit")} Payment Method" })
        <hr />
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>

        <div class="form-group">
            <label asp-for="Name" class="col-md-3 control-label"></label>
            <div class="col-md-8">
                <input asp-for="Name" class="form-control" autofocus="" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Description" class="col-md-3 control-label"></label>
            <div class="col-md-8">
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
        </div>

        



    </div>
    @await Html.PartialAsync("_ModalFooter", new ModalFooter { })
</form>

<script>
    $.validator.unobtrusive.parse("#frm");
</script>

Ecommerce_MVC_Core/Views/Units/_DeleteUnit.cshtml
<form asp-action="DeleteUnit" role="form">
    @Html.Partial("_ModalHeader", new ModalHeader { Heading = "Are you sure?" })

    <div class="modal-body form-horizontal">
        Are you want to delete <strong>@Model?</strong>
    </div>

    @Html.Partial("_ModalFooter", new ModalFooter { SubmitButtonText = "Delete" })
</form>