Ecommerce_MVC_Core/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ecommerce_MVC_Core.Code;
using Ecommerce_MVC_Core.Data;
using Ecommerce_MVC_Core.Models;
using Ecommerce_MVC_Core.Models.Admin;
using Ecommerce_MVC_Core.Repository;
using Ecommerce_MVC_Core.ViewModel.Public;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Ecommerce_MVC_Core.Controllers
{
    public class OrderController : Controller
    {
        //private readonly IRepository<Category> _repoCategory;
        //private readonly IRepository<Product> _repoProduct;
        //private readonly IRepository<Brand> _repoBrand;
        //private readonly IRepository<Unit> _repoUnit;

        //private readonly IRepository<ProductStock> _repoProductStock;
        //private readonly IRepository<ProductImage> _repoProductImage;
        //private readonly IRepository<Orders> _repoOrders;
        //private readonly IRepository<OrderDetails> _repoOrderDetails;
        //private readonly IRepository<Country> _repoCountry;
        //private readonly IRepository<City> _repoCity;
        //private readonly IRepository<Location> _repoLocation;
        //private readonly IRepository<PaymentMethod> _repoPaymentMethod;
        private readonly UserManager<ApplicationUsers> _userManager;

        private readonly IUnitOfWork _unitOfWork;


        public OrderController(IUnitOfWork unitOfWork, UserManager<ApplicationUsers> userManager)
        {
            _unitOfWork = unitOfWork;
            _userManager = userManager;
        }


        public IActionResult Index()
        {
            List<OrderDetailsViewModel> model = new List<OrderDetailsViewModel>();
            List<AddToCartViewModel> addToCartList = HttpContext.Session.Get<List<AddToCartViewModel>>("CartItem");
            int itemInCart = 0;
            var valu = HttpContext.Session.GetInt32("itemCount");
            if (valu != null)
            {
                itemInCart = valu.Value;
            }

            var dbProducts = _unitOfWork.Repository<Product>().Query()
                .Include(b => b.Brand)
                .Include( p => p.ProductImages)
                .Include(ps => ps.ProductStocks);
            if (addToCartList!=null)
            {
                addToCartList.ForEach(c =>
                {
                    OrderDetailsViewModel orderDetails=new OrderDetailsViewModel();
                    orderDetails.ProductId = c.ProductId;
                    orderDetails.ProductName = c.ProductName;
                    orderDetails.FinalPrice = c.FinalPrice;
                    orderDetails.Quantity = c.Quantity;
                    var product = dbProducts.FirstOrDefault(x => x.Id == c.ProductId);

                    if (product!=null)
                    {
                        orderDetails.BrandId = product.BrandId;
                        orderDetails.BrandName = product.Brand.Name;
                        orderDetails.Price = product.Price;
                        orderDetails.ImagePath =product.ProductImages.FirstOrDefault(x => x.ProductId == c.ProductId)
                            ?.ImagePath;
                        var pStock = product.ProductStocks.FirstOrDefault(x => x.ProductId == c.ProductId);
                        if (pStock!=null)
                        {
                            orderDetails.Stock = (pStock.InQuantity - pStock.OutQuantity) < 1
                                ? 0
                                : pStock.InQuantity - pStock.OutQuantity;
                        }
                        model.Add(orderDetails);
                    }
                });
            }

            return View(model);
        }

        [HttpPost]
        public IActionResult Index(IEnumerable<OrderDetailsViewModel> product)
        {
            List<AddToCartViewModel> addToCartList = HttpContext.Session.Get<List<AddToCartViewModel>>("CartItem");
            
            List <AddToCartViewModel> modelCart=new List<AddToCartViewModel>();

            int itemInCart = 0;
            double estimatePrice = 0;
            double totalPrice = 0;
            var valu = HttpContext.Session.GetInt32("itemCount");
            if (valu != null)
            {
                itemInCart = valu.Value;
            }
            HttpContext.Session.Set<List<AddToCartViewModel>>("CartItem", modelCart);
            foreach (var item in product)
            {
                AddToCartViewModel cart = new AddToCartViewModel();
                cart.ProductId = item.ProductId;
                cart.FinalPrice = item.FinalPrice;
                cart.ProductName = item.ProductName;
                cart.Quantity = item.Quantity;
                estimatePrice = item.Quantity * item.FinalPrice;
                totalPrice = totalPrice + estimatePrice;
                modelCart.Add(cart);
                
            }
            HttpContext.Session.Set<List<AddToCartViewModel>>("CartItem", modelCart);
            itemInCart = HttpContext.Session.Get<List<AddToCartViewModel>>("CartItem").Count;
            HttpContext.Session.SetInt32("itemCount", itemInCart);
            HttpContext.Session.SetInt32("TotalPrice",Convert.ToInt32(totalPrice));

            return RedirectToAction(nameof(NewOrder));
        }

        #region AddNewOrders
        [Authorize]
        public IActionResult NewOrder()
        {
            NewOrderViewModel model=new NewOrderViewModel();
            model.OrderDetailsList = GetItemOrderDetails();

            model.Countries  = _unitOfWork.Repository<Country>().GetAll().Select(c => new SelectListItem
            {
                Text = c.Name,
                Value = c.Id.ToString()

            }).OrderBy(x => x.Text).ToList();

            model.Countries.Add(new SelectListItem { Text = "--Select--", Value = "0", Selected = true });
            model.Cities = new List<SelectListItem>();
            model.Locations=new List<SelectListItem>();
            model.PaymentMethods = _unitOfWork.Repository<PaymentMethod>().GetAll().Select(p => new SelectListItem
            {
                Text = p.Name,
                Value = p.Id.ToString()

            }).OrderBy(s => s.Text).ToList();
            model.PaymentMethods.Add(new SelectListItem { Text = "--Select--", Value = "0",Selected = true});

            return View(model);
        }

        [Authorize]
        [HttpPost]
        public IActionResult NewOrder(NewOrderViewModel model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("","Something wrong");
                return View(model);
            }
            List<AddToCartViewModel> addToCartList = HttpContext.Session.Get<List<AddToCartViewModel>>("CartItem");

            if (addToCartList==null)
            {
                return RedirectToAction("Index", "Home");
            }

            var num = HttpContext.Session.GetInt32("TotalPrice");
            double totalPrice=0;
            if (num != null)
            {
                totalPrice =  Convert.ToDouble(num);
            }
            ApplicationUsers user = _userManager.GetUserAsync(HttpContext.User).Result;
            //Inserting Order
            Orders orders=new Orders
            {
                AddedDate = DateTime.Now,
                DeliveryAddress = model.DaliveryAddress,
                LocationId = model.LocationId,
                ModifiedDate = DateTime.Now,
                Number = GenerateRandomNo().ToString(),
                PaymentMethodId = model.PaymentMethodId,
                Total = totalPrice,
            };

            orders.UserId = user.Id;
            orders.DeliveryCharge = _unitOfWork.Repository<Location>().Find(x => x.Id == model.LocationId).Charge;
            _unitOfWork.Repository<Orders>().Insert(orders);
            
            //Inserting Order Details

            int oId=orders.Id;


            for (int i = 0; i < addToCartList.Count; i++)
            {

                OrderDetails orderDetails = new OrderDetails();

                orderDetails.AddedDate = DateTime.Now;
                orderDetails.ModifiedDate = DateTime.Now;
                orderDetails.OrderId = oId;
                orderDetails.ProductId = addToCartList[i].ProductId;
                orderDetails.Quantity = addToCartList[i].Quantity;
                orderDetails.Rate = addToCartList[i].FinalPrice;
                orderDetails.Remarks = "";

                _unitOfWork.Repository<OrderDetails>().Insert(orderDetails);
                    
             }
            

            addToCartList=new List<AddToCartViewModel>();
            HttpContext.Session.Set<List<AddToCartViewModel>>("CartItem", addToCartList);

           int itemInCart = HttpContext.Session.Get<List<AddToCartViewModel>>("CartItem").Count;
            HttpContext.Session.SetInt32("itemCount", itemInCart);
            HttpContext.Session.SetInt32("TotalPrice",0);

            return RedirectToAction("Index","Home");
        }

        public List<OrderDetailsViewModel> GetItemOrderDetails()
        {
            List<OrderDetailsViewModel> model = new List<OrderDetailsViewModel>();
            List<AddToCartViewModel> addToCartList = HttpContext.Session.Get<List<AddToCartViewModel>>("CartItem");
            int itemInCart = 0;
            var valu = HttpContext.Session.GetInt32("itemCount");
            if (valu != null)
            {
                itemInCart = valu.Value;
            }


            if (addToCartList != null)
            {
                var dbProducts = _unitOfWork.Repository<Product>().Query()
                    .Include(b => b.Brand)
                    .Include(p => p.ProductImages)
                    .Include(ps => ps.ProductStocks);

                addToCartList.ForEach(c =>
                {

Ecommerce_MVC_Core/ViewComponents/GetHeaderMainMenuViewComponent.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ecommerce_MVC_Core.Data;
using Ecommerce_MVC_Core.Models.Admin;
using Ecommerce_MVC_Core.Repository;
using Ecommerce_MVC_Core.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;

namespace Ecommerce_MVC_Core.ViewComponents
{
    public class GetHeaderMainMenuViewComponent : ViewComponent
    {
        
        private readonly IUnitOfWork _unitOfWork;
        private ApplicationDbContext _context;

        public GetHeaderMainMenuViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IViewComponentResult> InvokeAsync(int categoryId=0)
        {
            List<CategoryViewModel> categories = new List<CategoryViewModel>();
            if (categoryId>0)
            {
                categories = await GetLists(categoryId);
                return View("SubMenu", categories.OrderBy(x=>x.Name).ToList());
            }
            else
            {
                categories = await GetLists();
                return View("MainMenu", categories.OrderBy(x => x.Name).ToList());
            }
            
        }

        private Task<List<CategoryViewModel>> GetLists(int categoryId = 0)
        {
            List<CategoryViewModel> categories = new List<CategoryViewModel>();
            if (categoryId>0)
            {
                _unitOfWork.Repository<Category>().GetAll().Where(x => x.CategoryId == categoryId).ToList().ForEach(c =>
                {
                    CategoryViewModel category = new CategoryViewModel
                    {
                        Id = c.Id,
                        Name = c.Name,
                    };
                   
                        categories.Add(category);
                   
                });
                return Task.Run(() => categories);
            }
            else
            {
                _unitOfWork.Repository<Category>().GetAll().Where(x => x.CategoryId == null).ToList().ForEach(c =>
                {
                    CategoryViewModel category = new CategoryViewModel
                    {
                        Id = c.Id,
                        Name = c.Name,
                    };
                    
                        categories.Add(category);
                    
                });
                return Task.Run(() => categories);
            }
        }
    }
}

Ecommerce_MVC_Core/Views/Shared/Scripts.cshtml
<script src="~/js/public/modernizr.custom.js"></script>
<!-- Custom-JavaScript-File-Links -->
<!-- cart-js -->
<script src="~/js/public/minicart.min.js"></script>
<script>
    // Mini Cart
    paypal.minicart.render({
        action: '#'
    });

    if (~window.location.search.indexOf('reset=true')) {
        paypal.minicart.reset();
    }
</script>

<!-- //cart-js -->
<!-- script for responsive tabs -->
<script src="~/js/public/easy-responsive-tabs.js"></script>
<script>
    $(document).ready(function () {
        $('#horizontalTab').easyResponsiveTabs({
            type: 'default', //Types: default, vertical, accordion
            width: 'auto', //auto or any width like 600px
            fit: true,   // 100% fit in a container
            closed: 'accordion', // Start closed if in accordion view
            activate: function(event) { // Callback function if tab is switched
                var $tab = $(this);
                var $info = $('#tabInfo');
                var $name = $('span', $info);
                $name.text($tab.text());
                $info.show();
            }
        });
        $('#verticalTab').easyResponsiveTabs({
            type: 'vertical',
            width: 'auto',
            fit: true
        });
    });
</script>
<!-- //script for responsive tabs -->
<!-- stats -->
<script src="~/js/public/jquery.waypoints.min.js"></script>
<script src="~/js/public/jquery.countup.js"></script>
<script>
    $('.counter').countUp();
</script>
<!-- //stats -->
<!-- start-smoth-scrolling -->
<script type="text/javascript" src="~/js/public/move-top.js"></script>
<script type="text/javascript" src="~/js/public/jquery.easing.min.js"></script>
<script type="text/javascript">
    jQuery(document).ready(function($) {
        $(".scroll").click(function(event){
            event.preventDefault();
            $('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
        });
    });
</script>
<!-- here stars scrolling icon -->
<script type="text/javascript">
    $(document).ready(function() {
        /*
            var defaults = {
            containerID: 'toTop', // fading element id
            containerHoverID: 'toTopHover', // fading element hover id
            scrollSpeed: 1200,
            easingType: 'linear'
            };
        */

        $().UItoTop({ easingType: 'easeOutQuart' });

    });
</script>
<!-- //here ends scrolling icon -->

Ecommerce_MVC_Core/Views/Shared/SubLevelCategory.cshtml
@model IEnumerable<Ecommerce_MVC_Core.ViewModel.CategoryViewModel>


@foreach (var item in Model)
{

<a asp-controller="Home" asp-action="Product" asp-route-Category="@item.Id" class="list-group-item">@item.Name</a>
   

        @Html.Partial("SubLevelCategory", item.CategoryMenus)

    

}

Ecommerce_MVC_Core/Views/Shared/_HeaderMainMenu.cshtml
@model IEnumerable<Ecommerce_MVC_Core.ViewModel.CategoryViewModel>

    
@foreach (var item in Model)
{
        
           
    <div class="col-md-4">
        <b>@item.Name</b>
        <p>@item.Description</p>

        <ol>
           
        </ol>
    </div>

          
        
}

Ecommerce_MVC_Core/Views/Shared/_ImageView.cshtml
<form asp-action="">
    
</form>

<div class="col-md-4">
    <div class="img_style">
        <img src="~/uploads/ProductImages/@Model?" />
    </div>
</div>
<style>
    .img_style {
        left: 0;
        top: 0;
        
    }
    .img_style img {
        max-height: 450px;
    }
</style>

Ecommerce_MVC_Core/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] asp.net mvc</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/css/jquery-ui.css" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet/less" type="text/css" href="~/css/public/brandcrsole.less" />

        <link rel="stylesheet" href="~/css/public/flexslider.css" type="text/css" media="screen" />
        <link href="~/font-awesome/css/font-awesome.css" rel="stylesheet" />
        <link href="~/css/public/style.css" rel="stylesheet" />
        <link href="~/css/public/easy-responsive-tabs.css" rel="stylesheet" />


        <script src="~/lib/jquery/dist/jquery.js" type="text/javascript"></script>
        
        
        <script src="~/js/brandcrsole.js"></script>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
@Html.Partial("publicHeader")






<div>
    @RenderBody()
    <hr/>
    <footer>
        <div class="container text-center">
            <p>&copy; 2021 Mehdi</p>
        </div>
    </footer>
</div>
<environment include="Development">


    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>

    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/js/jquery-ui.js" type="text/javascript"></script>
    <script src="~/js/ModalPopup.js" type="text/javascript"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.js"></script>
    @Html.Partial("Scripts")
</environment>
<environment exclude="Development">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
    </script>
    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
    </script>

    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    <script src="~/js/ModalPopup.js" type="text/javascript" asp-append-version="true"></script>
</environment>

@RenderSection("Scripts", required: false)
</body>
</html>

Ecommerce_MVC_Core/Views/Shared/_Modal.cshtml
@model Ecommerce_MVC_Core.BootstrapModal.BootstrapModel

<div aria-hidden="true" aria-labelledby="@Model.AreaLabeledId" role="dialog" tabindex="-1" id="@Model.ID" class="modal fade">
    <div class="modal-dialog @Model.ModalSizeClass">
        <div class="modal-content">
        </div>
    </div>
</div> 

Ecommerce_MVC_Core/Views/Shared/_ModalFooter.cshtml
@model Ecommerce_MVC_Core.BootstrapModal.ModalFooter


<div class="modal-footer">
    <button data-dismiss="modal" id="@Model.CancelButtonID" class="btn btn-default" type="button">@Model.CancelButtonText</button>
    @if (!Model.OnlyCancelButton)
    {
        <button class="btn btn-success al" id="@Model.SubmitButtonID" type="submit">
            @Model.SubmitButtonText
        </button>
    }
</div> 
<script>
    $(".al").on("click", function() {
        $(".alert").removeClass("in").show();
        $(".alert").delay(600).addClass("in").fadeOut(5000);
    });
</script>

Ecommerce_MVC_Core/Views/Shared/_ModalHeader.cshtml
@model Ecommerce_MVC_Core.BootstrapModal.ModalHeader

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title">@Model.Heading</h4>
</div>

Ecommerce_MVC_Core/Views/Shared/_SubCategory.cshtml
@model IEnumerable<Ecommerce_MVC_Core.ViewModel.CategoryViewModel>

    
    @foreach (var item in Model)
    {
        
           
        <div class="col-md-4">
            <div class="list-group">
                <a asp-controller="Home" asp-action="Product" asp-route-Category="@item.Id" class="list-group-item active">@item.Name</a>
                @Html.Partial("SubLevelCategory", item.CategoryMenus)
            </div>
            
        </div>

          
        
    }

Ecommerce_MVC_Core/Views/Shared/publicHeader.cshtml
@using System.Security.Cryptography.X509Certificates
@using Ecommerce_MVC_Core.ViewModel
@using Ecommerce_MVC_Core.ViewModel.Public
@using Microsoft.AspNetCore.Http



<!-- header -->
<div class="header" id="home">
    <div class="container">
        <ul>
           @if (!Context.User.Identity.IsAuthenticated)
           {
               <li> <a id="createModel" asp-controller="Users" asp-action="Login"><i class="fa fa-unlock-alt" aria-hidden="true"></i> Sign In </a></li>
               <li> <a asp-controller="Users" asp-action="SignUp"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Sign Up </a></li>
           }
           else
           {
               <li> <a asp-controller="Users" asp-action="LogOut"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Logout</a></li>
           }
           
            <li><i class="fa fa-phone" aria-hidden="true"></i> Phone  : XXXXXXXXXXXX</li>
            <li><i class="fa fa-envelope-o" aria-hidden="true"></i> <a href="#"></a></li>
        </ul>
    </div>
</div>
<!-- //header -->
<!-- header-bot -->
<div class="header-bot">
    <div class="header-bot_inner_wthreeinfo_header_mid">
        <div class="col-md-4 header-middle">
            <form asp-controller="Home" asp-action="Product" method="get">
                <input type="search" name="search" placeholder="Search" required="">
                <input type="submit" value=" ">
                <div class="clearfix"></div>
            </form>
        </div>
        <!-- header-bot -->
        <div class="col-md-4 logo_agile">
            <h1>
                <a asp-controller="Home" asp-action="Index"><span>N</span>E<span>W</span> <span>B</span>R<span>A</span>N<span>d</span> <br /><i class="fa fa-shopping-bag top_logo_agile_bag" aria-hidden="true"></i></a>
            </h1>
        </div>
        <!-- header-bot -->
        <div class="col-md-4 agileits-social top_content">
            <ul class="social-nav model-3d-0 footer-social w3_agile_social">
                <li class="share">Share On : </li>
                <li>
                    <a href="#" class="facebook">
                        <div class="front">
                            <i class="fa fa-facebook" aria-hidden="true"></i>
                        </div>
                        <div class="back">
                            <i class="fa fa-facebook" aria-hidden="true"></i>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="#" class="twitter">
                        <div class="front">
                            <i class="fa fa-twitter" aria-hidden="true"></i>
                        </div>
                        <div class="back">
                            <i class="fa fa-twitter" aria-hidden="true"></i>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="#" class="instagram">
                        <div class="front">
                            <i class="fa fa-instagram" aria-hidden="true"></i>
                        </div>
                        <div class="back">
                            <i class="fa fa-instagram" aria-hidden="true"></i>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="#" class="pinterest">
                        <div class="front">
                            <i class="fa fa-linkedin" aria-hidden="true"></i>
                        </div>
                        <div class="back">
                            <i class="fa fa-linkedin" aria-hidden="true"></i>
                        </div>
                    </a>
                </li>
            </ul>
            


        </div>
        <div class="clearfix"></div>
    </div>
</div>
<!-- //header-bot -->
<!-- banner -->
<div class="ban-top">
    <div class="container">
        <div class="top_nav_left">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse menu--shylock" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav menu__list">
                            <li class="active menu__item menu__item--current"><a class="menu__link" asp-controller="Home" asp-action="Index">Home <span class="sr-only">(current)</span></a></li>
                            <li class=" menu__item"><a class="menu__link" asp-action="About" asp-controller="Home">About</a></li>


                                @await Component.InvokeAsync("GetHeaderMainMenu")
                            
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
        <div class="top_nav_right">
            <div class="wthreecartaits wthreecartaits2 cart cart box_1">
                <a asp-controller="Order" asp-action="Index">Check Out</a> 
                <span>
                    <b>
                        @{
                            int? item = Context.Session.GetInt32("itemCount");
                        }
                        @item
                    </b>
                </span>

            </div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<!-- //banner-top -->
@Html.Partial("Scripts")