Ecommerce_MVC_Core/Models/Admin/ProductMenual.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ecommerce_MVC_Core.Data;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Ecommerce_MVC_Core.Models.Admin
{
    public class ProductManual:BaseEntity
    {
        public int ProductId { get; set; }
        public string ManualName { get; set; }

        public Product Product { get; set; }

    }

    public class ProductManualMap
    {
        public ProductManualMap(EntityTypeBuilder<ProductManual> entityTypeBuilder)
        {
            entityTypeBuilder.HasKey(x =>x.Id);
            entityTypeBuilder.HasOne(x=>x.Product).WithOne(x=>x.ProductManual).HasForeignKey<ProductManual>(x=>x.ProductId);
            entityTypeBuilder.Property(x => x.ManualName);
        }
    }
}

Ecommerce_MVC_Core/Controllers/Admin/ProductMenualController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Ecommerce_MVC_Core.Data;
using Ecommerce_MVC_Core.Models.Admin;
using Ecommerce_MVC_Core.Repository;
using Ecommerce_MVC_Core.ViewModel;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;

namespace Ecommerce_MVC_Core.Controllers.Admin
{
    public class ProductMenualController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IHostingEnvironment _hostingEnv;

        public ProductMenualController(IUnitOfWork unitOfWork, IHostingEnvironment hostingEnv)
        {
            _unitOfWork = unitOfWork;
            _hostingEnv = hostingEnv;

        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async  Task<IActionResult> AddEditProductManual(int id)
        {
            ProductMenualViewModel model=new ProductMenualViewModel();
            if (id>0)
            {
                ProductManual productManual =await _unitOfWork.Repository<ProductManual>().GetSingleIncludeAsync(p=>p.Id==id,pro=>pro.Product);
                model.ProductId = productManual.ProductId;
                model.ProductName = productManual.Product.Name;

            }
            return View(model);
        }

        public async  Task<IActionResult> AddEditProductManual(int id, ProductMenualViewModel model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("","Something Wrong ");
                return View(model);
            }
            if (id>0)
            {
                ProductManual pManual =  await _unitOfWork.Repository<ProductManual>().GetByIdAsync(id);
                pManual.ProductId = model.ProductId;
                pManual.ModifiedDate=DateTime.Now;
            }
            else
            {
                ProductManual productManual=new ProductManual
                {
                    AddedDate = DateTime.Now,
                    ProductId = model.ProductId,
                    ModifiedDate = DateTime.Now
                };

                if (model.ProductFile != null && model.ProductFile.ContentType== "application/pdf")
                {
                    
                    var uploads = Path.Combine(_hostingEnv.WebRootPath, "uploads/ProductManuals");
                    var fileName = Path.Combine(uploads, model.ProductName + "_" + model.ProductId + ".pdf");
                    productManual.ManualName = Path.GetFileName(fileName);
                     await _unitOfWork.Repository<ProductManual>().InsertAsync(productManual);
                    using (var fileStream = new FileStream(Path.Combine(uploads, fileName), FileMode.Create))
                    {
                        await model.ProductFile.CopyToAsync(fileStream);
                    }
                    
                    //await model.ImageFile.CopyToAsync(new FileStream(fileName,FileMode.Create));
                }
                else
                {
                    ModelState.AddModelError("","Wrong file Type. Please Upload only PDF file");
                }
                
                    
                
            }

            return View();
        }

        //AutoComplete for Product
        [HttpGet]
        public JsonResult GetProducts(string term)
        {
            term = term.ToLower();
            var productList = _unitOfWork.Repository<Product>().GetAll().Where(x => x.Name.ToLower().StartsWith(term)).Select(x => new { label = x.Name, val = x.Id }).ToList();


            return Json(productList);
        }
    }
}

Ecommerce_MVC_Core/Views/ProductMenual/AddEditProductManual.cshtml
@model Ecommerce_MVC_Core.ViewModel.ProductMenualViewModel
@{
    ViewData["Title"] = "AddEditProductManual";
}

<form asp-action="AddEditProductManual" enctype="multipart/form-data">
    <div class="form-horizontal">
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>

        <div class="form-group">
            <label asp-for="ProductId" class="col-md-3 control-label"></label>
            <div class="col-md-8">
                <input type="text" id="txtProduct" asp-for="ProductName" class="form-control" autofocus="" />

                <input asp-for="ProductId" type="text" id="txtProductId" class="form-control" />
                <span asp-validation-for="ProductId" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="ProductFile" class="col-md-3 control-label"></label>
            <div class="col-md-8">
                <div>
                    <input type="file" asp-for="ProductFile" title="search image" id="file" />
                </div>
                <span asp-validation-for="ProductFile" class="text-danger"></span>
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit"/>
            </div>
        </div>
    </div>
</form>

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="/lib/jquery/dist/jquery.js"></script>
<script src="/js/jquery-ui.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#txtProduct").autocomplete({
            source: function (request, response) {
                $.ajax({
                    url: "/ProductImage/GetProducts",
                    type: "GET",
                    dataType: "json",
                    data: { term: request.term },
                    success: function (data) {
                        response($.map(data, function (item) {
                            console.log("Label " + item.label);
                            console.log("value " + item.val);
                            return { label: item.label, value: item.val };
                        }))

                    }
                })
            },

            select: function (event, ui) {

                $('#txtProductId').val(ui.item.value);
                $('#txtProduct').val(ui.item.label);
                return false;
            },
            messages: {
                noResults: "", results: function (resultsCount) { }
            }
        });
    })
</script>

Ecommerce_MVC_Core/Views/ProductMenual/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<div class="col-md-2">
    <a asp-controller="ProductMenual" asp-action="AddEditProductManual" class="btn btn-info">
        <i class="glyphicon glyphicon-plus"></i>Add
    </a>
</div>